# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify
  pod 'Starscream', '~> 3.0.2'
  pod 'lottie-ios'
  pod 'SpotifyLogin', '~> 0.1'
  pod 'Alamofire'
  pod 'BulletinBoard'
  pod 'SwiftyJSON'
end
